FROM nginx
MAINTAINER Author Uma Mahesh
LABEL this is just a basic portfolio
EXPOSE 80
WORKDIR /var/lib/jenkins/workspace/My_Job/src/main/webapp
COPY index.html javascript.js css/style.css /usr/share/nginx/html

